version: '3'
services:

  # APPLICATIONS #

  forecastle-ui:
    build: applications/web-server/
    volumes:
      - "web-volume:/usr/share/nginx/html"
    ports:
      - "8080:80"


  # COMPONENTS #

  dashboard:
    build: components/dashboard
    volumes:
      - ./components/dashboard/app
      - forecastle-ui-volume:/tmp/public

volumes:
  forecastle-ui-volume:

