version: '3'
services:

  # APPLICATIONS #

  forecastle-ui:
    build: applications/forecastle-ui/
    volumes:
      - "dashboard-volume:/usr/share/nginx/html"
    ports:
      - "8080:80"

  # COMPONENTS #

  dashboard:
    build: components/dashboard
    volumes:
      - ./components/dashboard:/app
      - dashboard-volume:/tmp/public

volumes:
  dashboard-volume:

